routes/movies_list_bp.py
from flask import Blueprint, render_template, jsonify, request
from flask_sqlalchemy import SQLAlchemy
from models.movie import Movie
from extensions import db
from flask_login import login_required


movies_list_bp = Blueprint("movies_list_bp", __name__)


# Task 2: /movies-list -> Display the data on the page from Azure (MSSQL)
# Movie list dashboard
@movies_list_bp.route("/")  # HOF
@login_required
def movie_list_page():
    movie_list = Movie.query.all()  # Select * from movies | movie_list iterator
    data = [movie.to_dict() for movie in movie_list]  # list of dictionaries

    return render_template("movie-list.html", movies=data)


# Task 3: /movies-list/99 -> Display the data on the page from Azure (MSSQL)
# Movie list detail
@movies_list_bp.route("/<id>")  # HOF
def movie_detail_page(id):
    filtered_movie = Movie.query.get(id)
    if filtered_movie:
        data = filtered_movie.to_dict()
        return render_template("filtered_movie.html", filtered_movie=data)
    else:
        return "<h1>Movie not found</h1>"


@movies_list_bp.route("/add", methods=["GET"])  # HOF
def add_movie():
    return render_template("add_movie.html")


@movies_list_bp.route("/delete", methods=["POST"])  # HOF
def delete_movie_by_id():
    print(request.form.get("movie_id"))
    id = request.form.get("movie_id")
    filtered_movie = Movie.query.get(id)
    if not filtered_movie:
        return "<h1>Movie not found</h1>", 404

    try:
        data = filtered_movie.to_dict()
        db.session.delete(filtered_movie)
        db.session.commit()  # Making the change (update/delete/create) permanent
        return f"<h1>{data['name']} Movie deleted Successfully</h1>"
    except Exception as e:
        db.session.rollback()  # Undo the change
        return f"<h1>Error happened {str(e)}</h1>", 500


@movies_list_bp.route("/success", methods=["POST"])  # HOF
def create_movie():
    # Creating a dictionary
    data = {
        "name": request.form.get("name"),
        "poster": request.form.get("poster"),
        "rating": request.form.get("rating"),
        "summary": request.form.get("summary"),
        "trailer": request.form.get("trailer"),
    }

    new_movie = Movie(**data)
    try:
        db.session.add(new_movie)
        db.session.commit()
        # movies.append(new_movie)
        return f"<h1>{data['name']} Movie added Successfully</h1>"
    except Exception as e:
        db.session.rollback()  # Undo the change
        return f"<h1>Error happened {str(e)}</h1>", 500


@movies_list_bp.route("/edit/<id>")
def edit_form(id):
    movie = Movie.query.get(id)
    data = movie.to_dict()
    return render_template("edit_form.html", movie=data)


@movies_list_bp.route("/update_movie_by_id", methods=["POST"])
def update_movie_by_id():
    movie_id = request.form.get("movie_id")
    movie = Movie.query.get(movie_id)

    if not movie:
        return "<h1>Movie not found</h1>", 404

    movie.name = request.form.get("name")
    movie.poster = request.form.get("poster")
    movie.rating = request.form.get("rating")
    movie.summary = request.form.get("summary")
    movie.trailer = request.form.get("trailer")

    try:
        db.session.commit()
        return "<h1>Movie updated successfully</h1>"
    except Exception as e:
        db.session.rollback()
        return f"Error occurred: {str(e)}", 500

templates/about.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <style>
      body {
        font-family: Roboto, sans-serif;
        display: grid;
        place-content: center;
        min-height: 100vh;
      }
 
      h1 {
        color: crimson;
      }
 
      .user-name {
        font-style: italic;
        font-weight: bold;
      }
 
      .user-pic {
        border-radius: 50%;
        height: 175px;
        aspect-ratio: 1 / 1;
        object-fit: cover;
      }
 
      .user-msg {
        font-size: 24px;
      }
 
      .user-container {
        /* background: crimson; */
      }
    </style>
  </head>
  <body>
    {% extends 'base.html' %}{% block body%}


    <!-- mustache -->
    {% for user in users %}
    <div class="user-container">
      <img class="user-pic" src="{{user.pic}}" alt="Profile picture" />
      <p class="user-msg">
        Hello,
        <span class="user-name"
          >{{user.name}} {{ "🚀" if user.pro else "🎊🎊" }} 
          <!-- ternary  operator. An expression is anything you can assign to a variable -->
        </span>
      </p>
    </div>
    {% endfor %}
    {% endblock %}
  </body>
</html>

templates/add_movie.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        .login-form{
            display:grid;
            gap: 12px;
        }
    </style>
</head>
<body>
    <!-- form only supports get and post but not put and delete -->
    <!-- for login, use post coz it is more secure -->
    <!-- with get, it goes in the url but post goes in the body -->
    <form class="login-form" action="{{url_for('movies_list_bp.create_movie')}}" method="post" >
            <input name="name" type="text" placeholder="name">
            <input name="poster" type="text" placeholder="poster">
            <input name="rating" type="number" step="0.1" placeholder="rating">
            <input name="summary" type="text" placeholder="summary">
            <input name="trailer" type="text" placeholder="trailer">
            <button type="submit">Submit</button>
    </form>
</body>
</html>

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %} </title>
    <link rel="stylesheet" href={{url_for('static',filename='style.css')}}>
    <link
    rel="stylesheet"
    href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css"
    integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N"
    crossorigin="anonymous"
  />
</head>
<body>
  <!-- whatever base says, that is the order -->
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Movies App</a>
    <button
      class="navbar-toggler"
      type="button"
      data-toggle="collapse"
      data-target="#navbarNavAltMarkup"
      aria-controls="navbarNavAltMarkup"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-link active" href="/profile"
          >Profile <span class="sr-only">(current)</span></a
        >
        <a class="nav-link" href="/movie-list">Movies</a>
      </div>
    </div>
  </nav>
  {% with messages = get_flashed_messages() %}
  {% if messages %}
    <ul class=flashes>
    {% for message in messages %}
      <li>{{ message }}</li>
    {% endfor %}
    </ul>
  {% endif %}
  {% endwith %}
  {% block redbox %}{% endblock %}
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script
    src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct"
    crossorigin="anonymous"
  ></script>
</body>
</html>

templates/dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        body{
            font-family: sans-serif;
        }
        .movie-container{
            /* background-color: orange; */
            width:300px;
        }
        img{
            height:540px;
            width:100%;
            object-fit: cover;
            border-radius: 24px;
            box-shadow: rgba(0, 0, 0, 0.24) 0px 3px 8x;
        }
        .movie-spec{
            display: flex;
            align-items: center;
            justify-content: space-between;
        }
        .movie-name{
            margin:0px;
        }
        .movie-list-container{
            display: flex;
            gap:10px;
            justify-content: space-around;
            flex-wrap: wrap;
        }
        .movie-actions{
            display:flex;
            justify-content: space-between;
        }
    </style>
</head>
<body>
   
    <div class="movie-list-container">
        {% for movie in movies %}
    <div class="movie-container">
        <img clas="movie-poster" src="{{movie['poster']}}" alt="{{movie.name}}">
        
        <div class="movie-spec">
            <h2 class="movie-name">{{movie['name']}}</h2> 
            <p>⭐{{movie['rating']}}</p>
        </div>
        <p>{{movie['summary']}}</p>
        <div class="movie-actions">
        <a href="/dashboard/{{movie.id}}"> View More ...</a>
        <form  action="{{url_for('delete_movie_by_id')}}" method="post">
            <input name="movie_id" type="text" value="{{movie.id}}" hidden>
        <button type="submit">delete</button>
        </form>
    </div>
    </div>
    {% endfor %}
</div>

</body>
</html>

templates/edit_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit Movie</title>
    <style>
        .edit-form{
            display: grid;
            gap: 12px;
        }
    </style>
</head>
<body>
    <form class="edit-form" action="{{ url_for('movies_list_bp.update_movie_by_id')}}" method="post">
        <input name="movie_id" type="text" value="{{movie.id}}" hidden>
        <input name="name" type="text" placeholder="Name">
        <input name="poster" type="text" placeholder="Poster">
        <input name="rating" type="number" step="0.1" placeholder="Rating">
        <input name="summary" type="text" placeholder="Summary">
        <input name="trailer" type="text" placeholder="Trailer">
        <button type="submit">Submit</button>
    </form>
</body>
</html>

templates/filtered_about.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <style>
      body {
        font-family: Roboto, sans-serif;
        display: grid;
        place-content: center;
        min-height: 100vh;
      }
 
      h1 {
        color: crimson;
      }
 
      .user-name {
        font-style: italic;
        font-weight: bold;
      }
 
      .user-pic {
        border-radius: 50%;
        height: 175px;
        aspect-ratio: 1 / 1;
        object-fit: cover;
      }
 
      .user-msg {
        font-size: 24px;
      }
 
      .user-container {
        /* background: crimson; */
      }
    </style>
  </head>
  <body>
    {% extends 'base.html' %}{% block body%}


    <!-- mustache -->
    <div class="user-container">
      <img class="user-pic" src="{{user.pic}}" alt="Profile picture" />
      <p class="user-msg">
        Hello,
        <span class="user-name"
          >{{user.name}} {{ "🚀" if user.pro else "🎊🎊" }} 
          <!-- ternary  operator. An expression is anything you can assign to a variable -->
        </span>
      </p>
    </div>
    {% endblock %}
  </body>
</html>

templates/filtered_movie.html
{% extends "base.html" %}
{% block title %}movie-detail{% endblock %}
{% block redbox %}
    <iframe 
    width="100%" 
    height="720"
    src="{{filtered_movie.trailer}}" 
    title="Ponniyin Selvan Teaser | #PS1 Tamil | Mani Ratnam | AR Rahman | Subaskaran | Madras Talkies" 
    frameborder="0" 
    allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" 
    allowfullscreen>
    </iframe>
    <div class="movie-detail-container">
        <div class="movie-spec">
            <h2 class="movie-name">{{filtered_movie.name}}</h2> 
            <p>⭐{{filtered_movie.rating}}</p>
        </div>
        <p>{{filtered_movie.summary}}</p>
    </div>
{% endblock %}

templates/forms.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        .login-form{
            display:grid;
            gap: 12px;
        }
    </style>
</head>
<body>
    <!-- form only supports get and post but not put and delete. Limitation of HTML -->
    <!-- for login, use post coz it is more secure -->
    <form class="login-form" action="{{url_for('users_bp.after_login')}}" method="post" >
            <input name="username" type="text" placeholder="username">
            <input name="password" type="password" placeholder="password">
            <button type="submit">Submit</button>
            <!-- submit it calls the action  -->
    </form>
</body>
</html>

templates/login1.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css"
      integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N"
      crossorigin="anonymous"
    />
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">Movies App</a>
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbarNavAltMarkup"
        aria-controls="navbarNavAltMarkup"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="nav-link active" href="/profile"
            >Profile <span class="sr-only">(current)</span></a
          >
          <a class="nav-link" href="/movie-list">Movies</a>
        </div>
      </div>
    </nav>
 
    <div class="container">
      <h1>Login</h1>
      <!-- action="" -> Submit to current url  -->
      <form method="POST" action="">
        <!-- Hidden input with token as value -->
        <!-- Validations -->
        {{form.hidden_tag()}} {% if form.username.errors %} {% for error in
        form.username.errors %}
        <div style="color: red">{{error}}</div>
        {% endfor %} {% endif %} {% if form.password.errors %} {% for error in
        form.password.errors %}
        <div style="color: red">{{error}}</div>
        {% endfor %} {% endif %}
        <div class="form-group">
          {{form.username.label}}: {{form.username(placeholder="Rashay",
          class="form-control is-invalid")}}
        </div>
        <div class="form-group">
          {{form.password.label}}: {{form.password(placeholder="Password",
          class="form-control")}}
        </div>
        {{form.submit(class="btn btn-primary")}}
      </form>
    </div>
 
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct"
      crossorigin="anonymous"
    ></script>
  </body>
</html>
 

templates/movie-list.html
    {% extends "base.html" %}
    {% block title %}movie-list{% endblock %}
    
    {% block redbox %}
    <div class="movie-list-container">
      {% for movie in movies %}
      <div class="movie-container">
        <img class="movie-poster" src="{{movie.poster}}" alt="{{movie.name}}" />
        <div class="movie-spec">
          <h2 class="movie-name">{{movie.name}}</h2>
          <p>⭐ {{movie.rating}}</p>
        </div>
        <p>{{movie.summary}}</p>
        <div class="movie-actions">
          <a href="/movie-list/{{movie.id}}">View More</a>
          <form
            action="{{url_for('movies_list_bp.delete_movie_by_id')}}"
            method="POST"
          >
            <input name="movie_id" type="text" value="{{movie.id}}" hidden />
            <button type="submit" class="btn btn-danger">Delete</button>
          </form>
        </div>
      </div>
      {% endfor %}
    </div>
    {% endblock %}

templates/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% extends 'base.html' %}{% block body%}
    <h1>{{name}}</h1>
    <h2>Hobbies</h2>
    <ul>
        {% for hobby in hobbies %}
        <li>{{hobby}}</li>
        {% endfor %}
        {% endblock %}
    </ul>
</body>
</html>

templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        .login-form{
            display:grid;
            gap: 12px;
        }
    </style>
</head>
<body>
    <!-- form only supports get and post but not put and delete. Limitation of HTML -->
    <!-- for login, use post coz it is more secure -->
    <form class="login-form" action="{{url_for('users_bp.after_register')}}" method="post" >
            <input name="username" type="text" placeholder="username">
            <input name="password" type="password" placeholder="password">
            <button type="submit">Submit</button>
            <!-- submit it calls the action  -->
    </form>
</body>
</html>

templates/register1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Register</h1>
    <!-- action="" refer to the current url -->
    <form method="POST" action=""> 
    <!-- hidden input field with token as value -->
    {{form.hidden_tag()}} 

    {% if form.username.errors %}
        {% for error in form.username.errors %}
            <div style="color:red">{{error}}</div>
        {% endfor %}
    {% endif %}

    {{form.username.label}}   
    {{form.username(placeholder="username")}}<br>
    {{form.password.label}}   
    {{form.password(placeholder="password")}}<br>
    {{form.submit()}}
    </form>
</body>
</html>

templates/sample.html
{% extends 'base.html' %}

{% block greenbox %}
<ul>
    <li>Gaming</li>
    <li>Coding</li>
    <li>Sleeping</li>
</ul>
{% endblcok %}

{% block redbox %}
<ol>
    <li>Python</li>
    <li>HTML</li>
    <li>CSS</li>
</ol>
{% endblcok %}